const ERR_INCORRECT_DATA = 400;
const ERR_NOT_FOUND = 404;
const ERR_CONFLICT_ERROR = 409;
const ERR_SERVER_ERROR = 500;

module.exports = {
  ERR_NOT_FOUND,
  ERR_INCORRECT_DATA,
  ERR_SERVER_ERROR,
  ERR_CONFLICT_ERROR,
};
